encyclopedia/urls.py
from django.urls import path

from . import views

app_name="encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.entry, name="entry"),
    path("newPage", views.newPage, name="newPage"),
    path("wiki/<str:entry>/editPage", views.editPage, name="editPage"),
    path("randomPage", views.randomPage, name="randomPage"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('wiki/', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from markdown2 import markdown
from django import forms
from pprint import pprint
import random


from . import util


class SearchForm(forms.Form):
    entryField = forms.CharField(label="Search")

class NewPageForm(forms.Form):
    pageTitle = forms.CharField(label="Title")
    pageContent = forms.CharField(widget=forms.Textarea, label="Page Content (Markdown)")

class EditPageForm(forms.Form):
    pageContent = forms.CharField(widget=forms.Textarea, label="Edit Page")



def index(request):

    # create a list of all entries
    allEntries = util.list_entries()
    # search function
    # check if the search bar has been used (POST request sent) 
    if request.method == "POST":
        # assign the search value a variable
        search = SearchForm(request.POST)
        # server side validatoin
        if search.is_valid():
            # check if the search value currently has a page
            searchValue = search.cleaned_data["entryField"]
            searchResult = util.get_entry(searchValue)
            if searchResult is None:
                # return a page with entries containing the substring of searchValue
                matchedEntries = []
                for entry in allEntries:
                    if searchValue in entry:
                        matchedEntries.append(entry)
                # if the searchValue isn't in any of the entries, return an error message.
                if len(matchedEntries) == 0:
                    matchedEntries = ["No entries matched your search result."]
                # otherwise, return the searchResult.html page with the results
                context = {
                    "entries": matchedEntries,
                    "searchForm": SearchForm()
                }

                return render(request, "encyclopedia/index.html", context)
            else:
                title = searchValue
                context = {
                'title': title,
                'entry': markdown(searchResult),
                "searchForm": SearchForm(),
            }
                return render(request, "encyclopedia/entry.html", context)
            
    else:        
        return render(request, "encyclopedia/index.html", {
            "entries": allEntries,
            "searchForm": SearchForm()
        })


def entry(request, entry):
    title = entry
    try:
        entry = markdown(util.get_entry(entry))
    except TypeError:
        context = {
            'entry': f"<h1>404 Page not Found</h1><p>There is no current page for: {entry}</p>",
            'title': 'error',
            "searchForm": SearchForm(),
        }
        return render(request, "encyclopedia/entry.html", context)
    else:
        context = {
            'title': title,
            'entry': entry,
            "searchForm": SearchForm(),
        }
        return render(request, "encyclopedia/entry.html", context)

def newPage(request):
    if request.method == "POST":
        # assign the page creation a variable
        result = NewPageForm(request.POST)
        # server side validatoin
        if result.is_valid():
            # check if the page title currently has a page
            titleValue = result.cleaned_data["pageTitle"]
            pageContent = result.cleaned_data["pageContent"]
            # check if the title is part of the already created pages
            allEntries = util.list_entries()
            if titleValue in allEntries:
                context = {
                    'entry': f"<h1>Error</h1><p>There is already an entry for: {titleValue}</p>",
                    'title': 'error'
                }
                return render(request, "encyclopedia/entry.html", context)
            # if there is currently no entry for that title, create one. 
            else:
                f = open(f"./entries/{titleValue}.md", "w")
                f.write(f"{pageContent}")
                f.close()

                context = {
                    'title': titleValue,
                    'entry': markdown(util.get_entry(titleValue)),
                    'searchForm': SearchForm()
                }
                return render(request, "encyclopedia/entry.html", context)
    

    context = {
        "newPageForm": NewPageForm(),
    }
    return render(request, "encyclopedia/newPage.html", context)



def editPage(request, entry):
    # if a form was submitted:
    if request.method == "POST":
        # assign the page creation a variable
        result = EditPageForm(request.POST)
        # server side validatoin
        if result.is_valid():
            # get the pageContent
            pageContent = result.cleaned_data["pageContent"]
            # save the new page content to the appropriatefile
            f = open(f"./entries/{entry}.md", "w")
            f.write(f"{pageContent}")
            f.close()

            context = {
                'title': entry,
                'entry': markdown(util.get_entry(entry)),
                "searchForm": SearchForm(),
            }
            return render(request, "encyclopedia/entry.html", context)



    text = util.get_entry(entry)
    context = {
        "editPageForm": EditPageForm(initial={'pageContent': text}),
        "title": entry,
    }
    return render(request, "encyclopedia/editPage.html", context)


def randomPage(request):
    entries = util.list_entries()
    entry = random.choice(entries)
    context = {
        "title": entry,
        "entry": markdown(util.get_entry(entry)),
        "searchForm": SearchForm(),
    }

    return render(request, "encyclopedia/entry.html", context)

encyclopedia/templates/encyclopedia/editPage.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
<form action="{% url 'encyclopedia:editPage' title %}", method="post">
    {% csrf_token %}
    {{ editPageForm }}
    <input type="submit">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    {{ title }}
{% endblock %}
{% block body %}
{{ entry|safe }}
<hr>
<a href="{% url 'encyclopedia:editPage' title %}">Edit this entry</a>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form class="search", action="{% url 'encyclopedia:index' %}", method="post">
                    {% csrf_token %}
                    {{ searchForm }}
                    <input type="submit">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newPage.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
newPage
{% endblock %}

{% block body %}
<h1>Create a New Entry</h1>
<hr>
<form action="{% url 'encyclopedia:newPage' %}", method="post">
        {% csrf_token %}
        {{ newPageForm }}
        <input type="submit">
</form>
{% endblock %}